#!/usr/bin/env bash

# setup

mkdir -p assets
touch assets/cool{1..3}.md assets/secret{1..5}.pdf assets/cool_script

mkdir -p assets/cool_dir{1..4}

cmhod +x assets/cool_script

# check all files in directory
# store what type of file it is
# regular, executable, directory
