#!/usr/bin/env bash

mkdir -p assets
touch assets/file{1..5}.txt assets/cool{1..3}.pdf

txt_files=( assets/*.txt )

IFS=$'\n'
echo "found ${#txt_files[*]} txt files"
for f in "${txt_files[@]}"; do
    echo "$f"
done
