#!/usr/bin/env bash

# IDS - internal field separator ->
# separates space, tabs and newlines

while IFS= read -r filename; do
    if [[ -f $filename ]]; then
        echo "'$filename' exists"
    else
        echo "'$filename' does not exist"
    fi
done
